import { Trophy, BookOpen, Palette, Earth } from "lucide-react"
export const categories = [
    {
        id: "sports",
        title: "Sports",
        description: "Test your knowledge of legendary athletes, iconic moments, and major tournaments across the world of sports. From football to tennis — are you game?",
        icon: Trophy,
        image: "/sports.webp",
        questionCount: 250,
        difficulty: "Mixed",
        gradient: "from-primary/10 via-primary/15 to-accent/10",
        hoverGradient: "from-primary/20 via-primary/25 to-accent/15",
        layout: "large",
        specialEffect: "spiral",
        particles: [
            { top: "1rem", right: "1rem", size: "w-1 h-1", color: "bg-primary/60", delay: "delay-100" },
            { top: "2rem", right: "3rem", size: "w-0.5 h-0.5", color: "bg-accent/60", delay: "delay-300" },
            { bottom: "2rem", left: "1.5rem", size: "w-1 h-1", color: "bg-primary/40", delay: "delay-500" },
        ],
    },
    {
        id: "geography",
        title: "Geography",
        description: "Explore continents, countries, capitals, and natural wonders. How well do you really know the world map?.",
        icon: Earth,
        questionCount: 180,
        image: "/geography.webp",
        difficulty: "Easy",
        gradient: "from-secondary/15 via-muted/20 to-secondary/10",
        hoverGradient: "from-secondary/25 via-muted/30 to-secondary/20",
        layout: "small",
        specialEffect: "spiral",
    },
    {
        id: "history",
        title: "History",
        description: "Travel through time and challenge your memory of key events, famous figures, and civilizations that shaped the world.",
        icon: BookOpen,
        questionCount: 320,
        difficulty: "Hard",
        image: "/history.webp",
        gradient: "from-accent/10 via-primary/10 to-accent/15",
        hoverGradient: "from-accent/20 via-primary/15 to-accent/25",
        layout: "small",
        specialEffect: "spiral",
    },
    {
        id: "arts",
        title: "Arts",
        description: "From classical masterpieces to modern design — see how well you know the artists, movements, and iconic works that define art history.",
        icon: Palette,
        questionCount: 150,
        image: '/arts.webp',
        difficulty: "Medium",
        gradient: "from-accent/15 via-secondary/10 to-primary/10",
        hoverGradient: "from-accent/25 via-secondary/20 to-primary/15",
        layout: "wide",
        specialEffect: "spiral",
    },
]